### =========================
### 1. LOGIN AS ADMIN
### =========================
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "aashwinsuperdu@gmail.com",
  "password": "ilikemyschoolvme"
}

### Copy the accessToken from response and paste below

@token = PASTE_ACCESS_TOKEN_HERE


### =========================
### 2. CREATE PRODUCT
### =========================
POST http://localhost:5000/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YzdjNzY3OTEzYzM4NjMzNzI3YWJiNyIsImVtYWlsIjoiYWFzaHdpbnN1cGVyZHVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc0NzA0ODE1LCJleHAiOjE3NzQ3MDU3MTV9.uO6WbhvjLvsv8XoAa0gEilGOpIifFhJZ6qL_MlPleh8
Content-Type: application/json

{
  "name": "Rengoku Flame Wallpaper",
  "series": "Demon Slayer",
  "price": 49,
  "img": "https://placeholder.com/preview.jpg"
}

### Copy the _id from response and paste below

@productId = 69c7d8c417a2cf18cd114e9e


### =========================
### 3. UPLOAD WALLPAPER
### =========================
POST http://localhost:5000/api/v1/upload/wallpaper
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YzdjNzY3OTEzYzM4NjMzNzI3YWJiNyIsImVtYWlsIjoiYWFzaHdpbnN1cGVyZHVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc0NzA0ODE1LCJleHAiOjE3NzQ3MDU3MTV9.uO6WbhvjLvsv8XoAa0gEilGOpIifFhJZ6qL_MlPleh8
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAniCart

------WebKitFormBoundaryAniCart
Content-Disposition: form-data; name="productId"

{{productId}}
------WebKitFormBoundaryAniCart
Content-Disposition: form-data; name="wallpaper"; filename="rengoku.jpg"
Content-Type: image/jpeg

< C:\Users\Superduash\Pictures\rengoku.jpg
------WebKitFormBoundaryAniCart--